name: BattlePlugin
version: '1.1'
main: org.kw906plugin.battlePlugin.BattlePlugin
api-version: '1.21.3'
commands:
  ability-battle:
    description: "능력 배틀 플러그인 제작자: KimWang906"
    usage: "/ability-battle [...options]"
    aliases: ab
    permission: ability-battle
    permission-message: "이 명령어를 사용할 권한이 없습니다!"
